version: '3'
services:
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3021 -b '0.0.0.0'"
    environment:
      - RAILS_ENV=development
      - BUNDLE_WITHOUT=production
    volumes:
      - .:/app
    ports:
      - 3021:3021
    depends_on:
      - db 
    tty: true
    stdin_open: true
  db:
    image: mysql:8.3
    platform: linux/amd64
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - quantum-path-app-db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "3954:3306"
volumes:
  quantum-path-app-db-volume:
